version: '2.1'

services:
  app:
    image: backend_1
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./apps:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=123456
    depends_on:
      - postgres
  
  postgres:
    image: postgres:11-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456